<?php
include 'auth.php';
include '../includes/db_connect.php';

/* -------- DATE FILTER -------- */
$from = $_GET['from'] ?? '';
$to   = $_GET['to'] ?? '';

$where = "WHERE p.status = 'SUCCESS'";

if (!empty($from) && !empty($to)) {
    $where .= " AND DATE(p.created_at) BETWEEN '$from' AND '$to'";
}

/* -------- TOTALS -------- */
$total = mysqli_fetch_assoc(mysqli_query($conn, "
    SELECT 
        COUNT(*) AS total_orders,
        SUM(p.amount) AS total_amount
    FROM payments p
    $where
"));

/* -------- DETAILS -------- */
$result = mysqli_query($conn, "
    SELECT 
        p.tran_id,
        p.amount,
        p.currency,
        p.payment_method,
        p.created_at,
        u.full_name,
        u.profile_id
    FROM payments p
    JOIN users u ON u.id = p.user_id
    $where
    ORDER BY p.created_at DESC
");
?>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Sales Report</title>

<style>
body {
    font-family: Arial, sans-serif;
    padding: 30px;
    background: #fff;
}

h1 {
    text-align: center;
    color: #ef4444;
    border-bottom: 3px solid #ef4444;
    padding-bottom: 10px;
}

.summary {
    display: flex;
    justify-content: space-between;
    margin: 20px 0;
}

.box {
    width: 48%;
    border: 1px solid #ddd;
    padding: 15px;
    text-align: center;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}

th, td {
    border: 1px solid #ccc;
    padding: 8px;
    text-align: center;
}

th {
    background: #1f2937;
    color: #fff;
}

.footer {
    margin-top: 30px;
    text-align: center;
    font-size: 12px;
    color: #777;
}

@media print {
    .no-print { display: none; }
}
</style>
</head>

<body onload="window.print()">

<h1>PerfectMatch Matrimony – Sales Report</h1>

<p style="text-align:center;">
    <?php if ($from && $to): ?>
        Report Period: <strong><?= htmlspecialchars($from) ?></strong> to <strong><?= htmlspecialchars($to) ?></strong>
    <?php else: ?>
        Report Period: <strong>All Time</strong>
    <?php endif; ?>
</p>

<div class="summary">
    <div class="box">
        <h3>Total Successful Payments</h3>
        <h2><?= (int)$total['total_orders'] ?></h2>
    </div>
    <div class="box">
        <h3>Total Sales</h3>
        <h2><?= number_format($total['total_amount'], 2) ?> BDT</h2>
    </div>
</div>

<table>
<thead>
<tr>
<th>#</th>
<th>Profile ID</th>
<th>Name</th>
<th>Transaction ID</th>
<th>Method</th>
<th>Amount</th>
<th>Date</th>
</tr>
</thead>
<tbody>

<?php if (mysqli_num_rows($result) > 0): $i=1; while($r=mysqli_fetch_assoc($result)): ?>
<tr>
<td><?= $i++ ?></td>
<td><?= htmlspecialchars($r['profile_id']) ?></td>
<td><?= htmlspecialchars($r['full_name']) ?></td>
<td><?= htmlspecialchars($r['tran_id']) ?></td>
<td><?= htmlspecialchars($r['payment_method']) ?></td>
<td><?= number_format($r['amount'],2) ?> <?= htmlspecialchars($r['currency']) ?></td>
<td><?= date('d M Y', strtotime($r['created_at'])) ?></td>
</tr>
<?php endwhile; else: ?>
<tr>
<td colspan="7">No sales found</td>
</tr>
<?php endif; ?>

</tbody>
</table>

<div class="footer">
    Generated by Admin Panel • <?= date('d M Y, h:i A') ?><br>
    © <?= date('Y') ?> PerfectMatch Matrimony
</div>

<div class="no-print" style="text-align:center;margin-top:20px;">
    <button onclick="window.print()">🖨 Print / Save as PDF</button>
</div>

</body>
</html>
